### ISSUE TITLE
How to set resolution and file format?

### ISSUE THREAD

**Issue by John-Colvin** [BlackEdder/plotd#1]
Are there any options available to make higher resolution plots and/or output different formats?

**Comment by BlackEdder** [comment]
Resolution (number of pixels) can be set with the margin-bounds command line switch:
--margin-bounds MARGINBOUNDS  Specific bounds (in pixel size) for the margins. Format (all in pixels): xmargin,xwidth,ymargin,yheight. Default values 70,400,70,400.

Currently only png is supported. I haven't yet had time to look into supporting other formats, although I think it shouldn't be to hard because it is using cairo.

**Comment by John-Colvin** [comment]
Cheers for the info.

The most important output formats for a lot of people are pdf and/or eps, for high-quality scalable embedding in latex and other type-setting systems.

**Comment by BlackEdder** [comment]
PDF (and SVG) format is now supported, although you also need to enable it in cairoD (see the README.md for more information).

EPS is not supported, since cairo does not support it. Could probably enable ps support, but I think pdf and svg should cover most vector graphics needs.
